#ifndef TYPE_H
#define TYPE_H

#ifndef NULL
#define NULL    (0)
#endif
#ifndef FALSE
#define FALSE   (0)
#endif
#ifndef TRUE
#define TRUE    (1)
#endif

/* Arm data types */
typedef unsigned char 		uint8;
typedef unsigned short int 	uint16;
typedef unsigned int 		uint32;
typedef char 		int8;
typedef short int 	int16;
typedef int 		int32; 
typedef unsigned char	BOOL;
typedef double   	float64;

#endif

